AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sending events from a Step Functions workflow to EventBridge

Resources:
  ConsumerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: code/
      Handler: consumer.handler
      Runtime: nodejs12.x
      Timeout: 3
      MemorySize: 128

  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "Send Step Functions transitions to EventBridge."
      EventPattern: 
        source:
          - "aws.states"
      Targets: 
        - Arn: !GetAtt ConsumerFunction.Arn
          Id: "ConsumerFunction"

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "ConsumerFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "EventRule"
          - "Arn"        
Outputs:
  ConsumerFunction:
    Description: ConsumerFunction function name
    Value: !Ref ConsumerFunction