version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ri-ex-3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18x8jmf1fa7ob"
s3_prefix = "ri-ex-3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"example-bucket-jbesw\" LoggingBucketName=\"example-bucket-jbesw-logs\""

