version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "http-apis-to-eventbridge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18x8jmf1fa7ob"
s3_prefix = "http-apis-to-eventbridge"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
